// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SomeChangesDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SomeChangesDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202008240630201_SomeChangesDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
