namespace Domain.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddCascade : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.AccountCancellationRequestAttachments", "AttachmentId", "dbo.Attachments");
            DropForeignKey("dbo.AccountCancellationRequestAttachments", "RequestId", "dbo.AccountCancellationRequests");
            DropForeignKey("dbo.AccountDisconnectRequestAttachments", "AttachmentId", "dbo.Attachments");
            DropForeignKey("dbo.AccountLossRequestAttachments", "AttachmentId", "dbo.Attachments");
            DropForeignKey("dbo.AccountRegistrationRequestAttachments", "AttachmentId", "dbo.Attachments");
            DropForeignKey("dbo.SoftwareDevelopmentRequestAttachments", "AttachmentId", "dbo.Attachments");
            DropForeignKey("dbo.SoftwareReworkRequestAttachments", "AttachmentId", "dbo.Attachments");
            DropForeignKey("dbo.AccountDisconnectRequestAttachments", "RequestId", "dbo.AccountDisconnectRequests");
            DropForeignKey("dbo.AccountDisconnectRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.AccountDisconnectRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.AccountDisconnectRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.AccountDisconnectRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.AccountDisconnectRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.ServicesApprovers", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.ExecutorGroupMembers", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.SubdivisionExecutors", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.Employees", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.ServicesApprovers", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.Services", "CategoryId", "dbo.Categories");
            DropForeignKey("dbo.ServicesExecutorGroups", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.Categories", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.ServicesExecutorGroups", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.ExecutorGroupMembers", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.SubdivisionExecutors", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.AccountLossRequestAttachments", "RequestId", "dbo.AccountLossRequests");
            DropForeignKey("dbo.AccountLossRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.AccountLossRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.AccountLossRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.AccountLossRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.AccountLossRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.AccountRegistrationRequestAttachments", "RequestId", "dbo.AccountRegistrationRequests");
            DropForeignKey("dbo.AccountRegistrationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.AccountRegistrationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.AccountRegistrationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.AccountRegistrationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.AccountRegistrationRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.SoftwareDevelopmentRequestAttachments", "RequestId", "dbo.SoftwareDevelopmentRequests");
            DropForeignKey("dbo.SoftwareDevelopmentRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.SoftwareDevelopmentRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.SoftwareDevelopmentRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.SoftwareDevelopmentRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.SoftwareDevelopmentRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.SoftwareReworkRequestAttachments", "RequestId", "dbo.SoftwareReworkRequests");
            DropForeignKey("dbo.SoftwareReworkRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.SoftwareReworkRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.SoftwareReworkRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.SoftwareReworkRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.SoftwareReworkRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.AccountCancellationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.AccountCancellationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.AccountCancellationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.AccountCancellationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.AccountCancellationRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.AccountCancellationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.AccountCancellationRequestLifeCycles", "RequestId", "dbo.AccountCancellationRequests");
            DropForeignKey("dbo.AccountDisconnectRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.AccountDisconnectRequestLifeCycles", "RequestId", "dbo.AccountDisconnectRequests");
            DropForeignKey("dbo.AccountLossRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.AccountLossRequestLifeCycles", "RequestId", "dbo.AccountLossRequests");
            DropForeignKey("dbo.AccountPermissions", "AccountId", "dbo.Accounts");
            DropForeignKey("dbo.AccountPermissions", "PermissionId", "dbo.Permissions");
            DropForeignKey("dbo.Accounts", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.AccountRegistrationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.AccountRegistrationRequestLifeCycles", "RequestId", "dbo.AccountRegistrationRequests");
            DropForeignKey("dbo.ComponentReplaceRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.ComponentReplaceRequestLifeCycles", "RequestId", "dbo.ComponentReplaceRequests");
            DropForeignKey("dbo.ComponentReplaceRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.ComponentReplaceRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.ComponentReplaceRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.ReplaceComponents", "RequestId", "dbo.ComponentReplaceRequests");
            DropForeignKey("dbo.ComponentReplaceRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.ComponentReplaceRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.ComponentReplaceRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.ReplaceComponents", "ComponentId", "dbo.Components");
            DropForeignKey("dbo.ConnectionEquipments", "EquipmentTypeId", "dbo.EquipmentTypes");
            DropForeignKey("dbo.ConnectionEquipments", "RequestId", "dbo.NetworkConnectionRequests");
            DropForeignKey("dbo.NetworkConnectionRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.NetworkConnectionRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.NetworkConnectionRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.NetworkConnectionRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.NetworkConnectionRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.NetworkConnectionRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.EmailRegistrationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.EmailRegistrationRequestLifeCycles", "RequestId", "dbo.EmailRegistrationRequests");
            DropForeignKey("dbo.EmailRegistrationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.EmailRegistrationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.EmailRegistrationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.EmailRegistrationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EmailRegistrationRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.EmailSizeIncreaseRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.EmailSizeIncreaseRequestLifeCycles", "RequestId", "dbo.EmailSizeIncreaseRequests");
            DropForeignKey("dbo.EmailSizeIncreaseRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.EmailSizeIncreaseRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.EmailSizeIncreaseRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.EmailSizeIncreaseRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EmailSizeIncreaseRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.EquipmentInstallationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.EquipmentInstallationRequestLifeCycles", "RequestId", "dbo.EquipmentInstallationRequests");
            DropForeignKey("dbo.EquipmentInstallationRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.EquipmentInstallationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.InstallationEquipments", "RequestId", "dbo.EquipmentInstallationRequests");
            DropForeignKey("dbo.EquipmentInstallationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.EquipmentInstallationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.EquipmentInstallationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EquipmentInstallationRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.InstallationEquipments", "EquipmentTypeId", "dbo.EquipmentTypes");
            DropForeignKey("dbo.EquipmentRefillRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.EquipmentRefillRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.EquipmentRefillRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.RefillEquipments", "RequestId", "dbo.EquipmentRefillRequests");
            DropForeignKey("dbo.EquipmentRefillRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.EquipmentRefillRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EquipmentRefillRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.EquipmentRefillRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.EquipmentRefillRequestLifeCycles", "RequestId", "dbo.EquipmentRefillRequests");
            DropForeignKey("dbo.EquipmentRepairRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.EquipmentRepairRequestLifeCycles", "RequestId", "dbo.EquipmentRepairRequests");
            DropForeignKey("dbo.EquipmentRepairRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.EquipmentRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.EquipmentRepairRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.RepairEquipments", "RequestId", "dbo.EquipmentRepairRequests");
            DropForeignKey("dbo.EquipmentRepairRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.EquipmentRepairRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EquipmentRepairRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.RepairEquipments", "ConsumableId", "dbo.Consumables");
            DropForeignKey("dbo.EquipmentReplaceRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.EquipmentReplaceRequestLifeCycles", "RequestId", "dbo.EquipmentReplaceRequests");
            DropForeignKey("dbo.EquipmentReplaceRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.EquipmentReplaceRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.EquipmentReplaceRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.ReplaceEquipments", "RequestId", "dbo.EquipmentReplaceRequests");
            DropForeignKey("dbo.EquipmentReplaceRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.EquipmentReplaceRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EquipmentReplaceRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.ReplaceEquipments", "EquipmentTypeId", "dbo.EquipmentTypes");
            DropForeignKey("dbo.Equipments", "EquipmentTypeId", "dbo.EquipmentTypes");
            DropForeignKey("dbo.HoldingPhoneLineRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.HoldingPhoneLineRequestLifeCycles", "RequestId", "dbo.HoldingPhoneLineRequests");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.NetworkConnectionRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.NetworkConnectionRequestLifeCycles", "RequestId", "dbo.NetworkConnectionRequests");
            DropForeignKey("dbo.PhoneLineRepairRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.PhoneLineRepairRequestLifeCycles", "RequestId", "dbo.PhoneLineRepairRequests");
            DropForeignKey("dbo.PhoneLineRepairRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.PhoneLineRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.PhoneLineRepairRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.PhoneLineRepairRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.PhoneLineRepairRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.PhoneLineRepairRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.PhoneNumberAllocationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.PhoneNumberAllocationRequestLifeCycles", "RequestId", "dbo.PhoneNumberAllocationRequests");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.PhoneRepairRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.PhoneRepairRequestLifeCycles", "RequestId", "dbo.PhoneRepairRequests");
            DropForeignKey("dbo.PhoneRepairRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.PhoneRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.PhoneRepairRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.PhoneRepairRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.PhoneRepairRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.PhoneRepairRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.RefuelingLimits", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.RequestsView", "ClientId", "dbo.Employees");
            DropForeignKey("dbo.RequestsView", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.RequestsView", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.RequestsView", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.RequestsView", "StatusId", "dbo.Status");
            DropForeignKey("dbo.RequestsView", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.SoftwareDevelopmentRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.SoftwareDevelopmentRequestLifeCycles", "RequestId", "dbo.SoftwareDevelopmentRequests");
            DropForeignKey("dbo.SoftwareReworkRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.SoftwareReworkRequestLifeCycles", "RequestId", "dbo.SoftwareReworkRequests");
            DropForeignKey("dbo.VideoCommunicationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.VideoCommunicationRequestLifeCycles", "RequestId", "dbo.VideoCommunicationRequests");
            DropForeignKey("dbo.VideoCommunicationRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.VideoCommunicationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.VideoCommunicationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.VideoCommunicationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.VideoCommunicationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.VideoCommunicationRequests", "SubdivisionId", "dbo.Subdivisions");
            AddForeignKey("dbo.AccountCancellationRequestAttachments", "AttachmentId", "dbo.Attachments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountCancellationRequestAttachments", "RequestId", "dbo.AccountCancellationRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountDisconnectRequestAttachments", "AttachmentId", "dbo.Attachments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountLossRequestAttachments", "AttachmentId", "dbo.Attachments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountRegistrationRequestAttachments", "AttachmentId", "dbo.Attachments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareDevelopmentRequestAttachments", "AttachmentId", "dbo.Attachments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareReworkRequestAttachments", "AttachmentId", "dbo.Attachments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountDisconnectRequestAttachments", "RequestId", "dbo.AccountDisconnectRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountDisconnectRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountDisconnectRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountDisconnectRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountDisconnectRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountDisconnectRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ServicesApprovers", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ExecutorGroupMembers", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SubdivisionExecutors", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Employees", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ServicesApprovers", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Services", "CategoryId", "dbo.Categories", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ServicesExecutorGroups", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Categories", "BranchId", "dbo.Branches", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ServicesExecutorGroups", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ExecutorGroupMembers", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SubdivisionExecutors", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.AccountLossRequestAttachments", "RequestId", "dbo.AccountLossRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountLossRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountLossRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountLossRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountLossRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountLossRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountRegistrationRequestAttachments", "RequestId", "dbo.AccountRegistrationRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountRegistrationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountRegistrationRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountRegistrationRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountRegistrationRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountRegistrationRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareDevelopmentRequestAttachments", "RequestId", "dbo.SoftwareDevelopmentRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareDevelopmentRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareDevelopmentRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareDevelopmentRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareDevelopmentRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareDevelopmentRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareReworkRequestAttachments", "RequestId", "dbo.SoftwareReworkRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareReworkRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareReworkRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareReworkRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareReworkRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareReworkRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountCancellationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountCancellationRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountCancellationRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountCancellationRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountCancellationRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountCancellationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountCancellationRequestLifeCycles", "RequestId", "dbo.AccountCancellationRequests", "Id", cascadeDelete: false);
            AddForeignKey("dbo.AccountDisconnectRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountDisconnectRequestLifeCycles", "RequestId", "dbo.AccountDisconnectRequests", "Id", cascadeDelete: false);
            AddForeignKey("dbo.AccountLossRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountLossRequestLifeCycles", "RequestId", "dbo.AccountLossRequests", "Id", cascadeDelete: false);
            AddForeignKey("dbo.AccountPermissions", "AccountId", "dbo.Accounts", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountPermissions", "PermissionId", "dbo.Permissions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Accounts", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountRegistrationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AccountRegistrationRequestLifeCycles", "RequestId", "dbo.AccountRegistrationRequests", "Id", cascadeDelete: false);
            AddForeignKey("dbo.ComponentReplaceRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ComponentReplaceRequestLifeCycles", "RequestId", "dbo.ComponentReplaceRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ComponentReplaceRequests", "CampusId", "dbo.Campus", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ComponentReplaceRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ComponentReplaceRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ReplaceComponents", "RequestId", "dbo.ComponentReplaceRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ComponentReplaceRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ComponentReplaceRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ComponentReplaceRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.ReplaceComponents", "ComponentId", "dbo.Components", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ConnectionEquipments", "EquipmentTypeId", "dbo.EquipmentTypes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ConnectionEquipments", "RequestId", "dbo.NetworkConnectionRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.NetworkConnectionRequests", "CampusId", "dbo.Campus", "Id", cascadeDelete: true);
            AddForeignKey("dbo.NetworkConnectionRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.NetworkConnectionRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.NetworkConnectionRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.NetworkConnectionRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.NetworkConnectionRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailRegistrationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailRegistrationRequestLifeCycles", "RequestId", "dbo.EmailRegistrationRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailRegistrationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailRegistrationRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailRegistrationRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailRegistrationRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailRegistrationRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.EmailSizeIncreaseRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailSizeIncreaseRequestLifeCycles", "RequestId", "dbo.EmailSizeIncreaseRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailSizeIncreaseRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailSizeIncreaseRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailSizeIncreaseRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailSizeIncreaseRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmailSizeIncreaseRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.EquipmentInstallationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentInstallationRequestLifeCycles", "RequestId", "dbo.EquipmentInstallationRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentInstallationRequests", "CampusId", "dbo.Campus", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentInstallationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.InstallationEquipments", "RequestId", "dbo.EquipmentInstallationRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentInstallationRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentInstallationRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentInstallationRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentInstallationRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.InstallationEquipments", "EquipmentTypeId", "dbo.EquipmentTypes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRefillRequests", "CampusId", "dbo.Campus", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRefillRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRefillRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RefillEquipments", "RequestId", "dbo.EquipmentRefillRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRefillRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRefillRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRefillRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.EquipmentRefillRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRefillRequestLifeCycles", "RequestId", "dbo.EquipmentRefillRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRepairRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRepairRequestLifeCycles", "RequestId", "dbo.EquipmentRepairRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRepairRequests", "CampusId", "dbo.Campus", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRepairRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RepairEquipments", "RequestId", "dbo.EquipmentRepairRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRepairRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRepairRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentRepairRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.RepairEquipments", "ConsumableId", "dbo.Consumables", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentReplaceRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentReplaceRequestLifeCycles", "RequestId", "dbo.EquipmentReplaceRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentReplaceRequests", "CampusId", "dbo.Campus", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentReplaceRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentReplaceRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ReplaceEquipments", "RequestId", "dbo.EquipmentReplaceRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentReplaceRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentReplaceRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EquipmentReplaceRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.ReplaceEquipments", "EquipmentTypeId", "dbo.EquipmentTypes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Equipments", "EquipmentTypeId", "dbo.EquipmentTypes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HoldingPhoneLineRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HoldingPhoneLineRequestLifeCycles", "RequestId", "dbo.HoldingPhoneLineRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HoldingPhoneLineRequests", "CampusId", "dbo.Campus", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HoldingPhoneLineRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HoldingPhoneLineRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HoldingPhoneLineRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HoldingPhoneLineRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HoldingPhoneLineRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.NetworkConnectionRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.NetworkConnectionRequestLifeCycles", "RequestId", "dbo.NetworkConnectionRequests", "Id", cascadeDelete: false);
            AddForeignKey("dbo.PhoneLineRepairRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneLineRepairRequestLifeCycles", "RequestId", "dbo.PhoneLineRepairRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneLineRepairRequests", "CampusId", "dbo.Campus", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneLineRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneLineRepairRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneLineRepairRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneLineRepairRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneLineRepairRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.PhoneNumberAllocationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneNumberAllocationRequestLifeCycles", "RequestId", "dbo.PhoneNumberAllocationRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "CampusId", "dbo.Campus", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.PhoneRepairRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneRepairRequestLifeCycles", "RequestId", "dbo.PhoneRepairRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneRepairRequests", "CampusId", "dbo.Campus", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneRepairRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneRepairRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneRepairRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PhoneRepairRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
            AddForeignKey("dbo.RefuelingLimits", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareDevelopmentRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareDevelopmentRequestLifeCycles", "RequestId", "dbo.SoftwareDevelopmentRequests", "Id", cascadeDelete: false);
            AddForeignKey("dbo.SoftwareReworkRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SoftwareReworkRequestLifeCycles", "RequestId", "dbo.SoftwareReworkRequests", "Id", cascadeDelete: false);
            AddForeignKey("dbo.VideoCommunicationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VideoCommunicationRequestLifeCycles", "RequestId", "dbo.VideoCommunicationRequests", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VideoCommunicationRequests", "CampusId", "dbo.Campus", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VideoCommunicationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VideoCommunicationRequests", "PriorityId", "dbo.Priorities", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VideoCommunicationRequests", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VideoCommunicationRequests", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VideoCommunicationRequests", "SubdivisionId", "dbo.Subdivisions", "Id", cascadeDelete: false);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.VideoCommunicationRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.VideoCommunicationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.VideoCommunicationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.VideoCommunicationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.VideoCommunicationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.VideoCommunicationRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.VideoCommunicationRequestLifeCycles", "RequestId", "dbo.VideoCommunicationRequests");
            DropForeignKey("dbo.VideoCommunicationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.SoftwareReworkRequestLifeCycles", "RequestId", "dbo.SoftwareReworkRequests");
            DropForeignKey("dbo.SoftwareReworkRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.SoftwareDevelopmentRequestLifeCycles", "RequestId", "dbo.SoftwareDevelopmentRequests");
            DropForeignKey("dbo.SoftwareDevelopmentRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.RequestsView", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.RequestsView", "StatusId", "dbo.Status");
            DropForeignKey("dbo.RequestsView", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.RequestsView", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.RequestsView", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.RequestsView", "ClientId", "dbo.Employees");
            DropForeignKey("dbo.RefuelingLimits", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.PhoneRepairRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.PhoneRepairRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.PhoneRepairRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.PhoneRepairRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.PhoneRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.PhoneRepairRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.PhoneRepairRequestLifeCycles", "RequestId", "dbo.PhoneRepairRequests");
            DropForeignKey("dbo.PhoneRepairRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.PhoneNumberAllocationRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.PhoneNumberAllocationRequestLifeCycles", "RequestId", "dbo.PhoneNumberAllocationRequests");
            DropForeignKey("dbo.PhoneNumberAllocationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.PhoneLineRepairRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.PhoneLineRepairRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.PhoneLineRepairRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.PhoneLineRepairRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.PhoneLineRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.PhoneLineRepairRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.PhoneLineRepairRequestLifeCycles", "RequestId", "dbo.PhoneLineRepairRequests");
            DropForeignKey("dbo.PhoneLineRepairRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.NetworkConnectionRequestLifeCycles", "RequestId", "dbo.NetworkConnectionRequests");
            DropForeignKey("dbo.NetworkConnectionRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.HoldingPhoneLineRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.HoldingPhoneLineRequestLifeCycles", "RequestId", "dbo.HoldingPhoneLineRequests");
            DropForeignKey("dbo.HoldingPhoneLineRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.Equipments", "EquipmentTypeId", "dbo.EquipmentTypes");
            DropForeignKey("dbo.ReplaceEquipments", "EquipmentTypeId", "dbo.EquipmentTypes");
            DropForeignKey("dbo.EquipmentReplaceRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.EquipmentReplaceRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EquipmentReplaceRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.ReplaceEquipments", "RequestId", "dbo.EquipmentReplaceRequests");
            DropForeignKey("dbo.EquipmentReplaceRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.EquipmentReplaceRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.EquipmentReplaceRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.EquipmentReplaceRequestLifeCycles", "RequestId", "dbo.EquipmentReplaceRequests");
            DropForeignKey("dbo.EquipmentReplaceRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.RepairEquipments", "ConsumableId", "dbo.Consumables");
            DropForeignKey("dbo.EquipmentRepairRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.EquipmentRepairRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EquipmentRepairRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.RepairEquipments", "RequestId", "dbo.EquipmentRepairRequests");
            DropForeignKey("dbo.EquipmentRepairRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.EquipmentRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.EquipmentRepairRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.EquipmentRepairRequestLifeCycles", "RequestId", "dbo.EquipmentRepairRequests");
            DropForeignKey("dbo.EquipmentRepairRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.EquipmentRefillRequestLifeCycles", "RequestId", "dbo.EquipmentRefillRequests");
            DropForeignKey("dbo.EquipmentRefillRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.EquipmentRefillRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.EquipmentRefillRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EquipmentRefillRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.RefillEquipments", "RequestId", "dbo.EquipmentRefillRequests");
            DropForeignKey("dbo.EquipmentRefillRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.EquipmentRefillRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.EquipmentRefillRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.InstallationEquipments", "EquipmentTypeId", "dbo.EquipmentTypes");
            DropForeignKey("dbo.EquipmentInstallationRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.EquipmentInstallationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EquipmentInstallationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.EquipmentInstallationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.InstallationEquipments", "RequestId", "dbo.EquipmentInstallationRequests");
            DropForeignKey("dbo.EquipmentInstallationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.EquipmentInstallationRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.EquipmentInstallationRequestLifeCycles", "RequestId", "dbo.EquipmentInstallationRequests");
            DropForeignKey("dbo.EquipmentInstallationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.EmailSizeIncreaseRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.EmailSizeIncreaseRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EmailSizeIncreaseRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.EmailSizeIncreaseRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.EmailSizeIncreaseRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.EmailSizeIncreaseRequestLifeCycles", "RequestId", "dbo.EmailSizeIncreaseRequests");
            DropForeignKey("dbo.EmailSizeIncreaseRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.EmailRegistrationRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.EmailRegistrationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.EmailRegistrationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.EmailRegistrationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.EmailRegistrationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.EmailRegistrationRequestLifeCycles", "RequestId", "dbo.EmailRegistrationRequests");
            DropForeignKey("dbo.EmailRegistrationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.NetworkConnectionRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.NetworkConnectionRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.NetworkConnectionRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.NetworkConnectionRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.NetworkConnectionRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.NetworkConnectionRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.ConnectionEquipments", "RequestId", "dbo.NetworkConnectionRequests");
            DropForeignKey("dbo.ConnectionEquipments", "EquipmentTypeId", "dbo.EquipmentTypes");
            DropForeignKey("dbo.ReplaceComponents", "ComponentId", "dbo.Components");
            DropForeignKey("dbo.ComponentReplaceRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.ComponentReplaceRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.ComponentReplaceRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.ReplaceComponents", "RequestId", "dbo.ComponentReplaceRequests");
            DropForeignKey("dbo.ComponentReplaceRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.ComponentReplaceRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.ComponentReplaceRequests", "CampusId", "dbo.Campus");
            DropForeignKey("dbo.ComponentReplaceRequestLifeCycles", "RequestId", "dbo.ComponentReplaceRequests");
            DropForeignKey("dbo.ComponentReplaceRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.AccountRegistrationRequestLifeCycles", "RequestId", "dbo.AccountRegistrationRequests");
            DropForeignKey("dbo.AccountRegistrationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.Accounts", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.AccountPermissions", "PermissionId", "dbo.Permissions");
            DropForeignKey("dbo.AccountPermissions", "AccountId", "dbo.Accounts");
            DropForeignKey("dbo.AccountLossRequestLifeCycles", "RequestId", "dbo.AccountLossRequests");
            DropForeignKey("dbo.AccountLossRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.AccountDisconnectRequestLifeCycles", "RequestId", "dbo.AccountDisconnectRequests");
            DropForeignKey("dbo.AccountDisconnectRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.AccountCancellationRequestLifeCycles", "RequestId", "dbo.AccountCancellationRequests");
            DropForeignKey("dbo.AccountCancellationRequestLifeCycles", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.AccountCancellationRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.AccountCancellationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.AccountCancellationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.AccountCancellationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.AccountCancellationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.SoftwareReworkRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.SoftwareReworkRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.SoftwareReworkRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.SoftwareReworkRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.SoftwareReworkRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.SoftwareReworkRequestAttachments", "RequestId", "dbo.SoftwareReworkRequests");
            DropForeignKey("dbo.SoftwareDevelopmentRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.SoftwareDevelopmentRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.SoftwareDevelopmentRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.SoftwareDevelopmentRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.SoftwareDevelopmentRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.SoftwareDevelopmentRequestAttachments", "RequestId", "dbo.SoftwareDevelopmentRequests");
            DropForeignKey("dbo.AccountRegistrationRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.AccountRegistrationRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.AccountRegistrationRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.AccountRegistrationRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.AccountRegistrationRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.AccountRegistrationRequestAttachments", "RequestId", "dbo.AccountRegistrationRequests");
            DropForeignKey("dbo.AccountLossRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.AccountLossRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.AccountLossRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.AccountLossRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.AccountLossRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.AccountLossRequestAttachments", "RequestId", "dbo.AccountLossRequests");
            DropForeignKey("dbo.SubdivisionExecutors", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.ExecutorGroupMembers", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.ServicesExecutorGroups", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.Categories", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.ServicesExecutorGroups", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.Services", "CategoryId", "dbo.Categories");
            DropForeignKey("dbo.ServicesApprovers", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.Employees", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.SubdivisionExecutors", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.ExecutorGroupMembers", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.ServicesApprovers", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.AccountDisconnectRequests", "SubdivisionId", "dbo.Subdivisions");
            DropForeignKey("dbo.AccountDisconnectRequests", "StatusId", "dbo.Status");
            DropForeignKey("dbo.AccountDisconnectRequests", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.AccountDisconnectRequests", "PriorityId", "dbo.Priorities");
            DropForeignKey("dbo.AccountDisconnectRequests", "ExecutorGroupId", "dbo.ExecutorGroups");
            DropForeignKey("dbo.AccountDisconnectRequestAttachments", "RequestId", "dbo.AccountDisconnectRequests");
            DropForeignKey("dbo.SoftwareReworkRequestAttachments", "AttachmentId", "dbo.Attachments");
            DropForeignKey("dbo.SoftwareDevelopmentRequestAttachments", "AttachmentId", "dbo.Attachments");
            DropForeignKey("dbo.AccountRegistrationRequestAttachments", "AttachmentId", "dbo.Attachments");
            DropForeignKey("dbo.AccountLossRequestAttachments", "AttachmentId", "dbo.Attachments");
            DropForeignKey("dbo.AccountDisconnectRequestAttachments", "AttachmentId", "dbo.Attachments");
            DropForeignKey("dbo.AccountCancellationRequestAttachments", "RequestId", "dbo.AccountCancellationRequests");
            DropForeignKey("dbo.AccountCancellationRequestAttachments", "AttachmentId", "dbo.Attachments");
            AddForeignKey("dbo.VideoCommunicationRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.VideoCommunicationRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.VideoCommunicationRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.VideoCommunicationRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.VideoCommunicationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.VideoCommunicationRequests", "CampusId", "dbo.Campus", "Id");
            AddForeignKey("dbo.VideoCommunicationRequestLifeCycles", "RequestId", "dbo.VideoCommunicationRequests", "Id");
            AddForeignKey("dbo.VideoCommunicationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.SoftwareReworkRequestLifeCycles", "RequestId", "dbo.SoftwareReworkRequests", "Id");
            AddForeignKey("dbo.SoftwareReworkRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.SoftwareDevelopmentRequestLifeCycles", "RequestId", "dbo.SoftwareDevelopmentRequests", "Id");
            AddForeignKey("dbo.SoftwareDevelopmentRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.RequestsView", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.RequestsView", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.RequestsView", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.RequestsView", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.RequestsView", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.RequestsView", "ClientId", "dbo.Employees", "Id");
            AddForeignKey("dbo.RefuelingLimits", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.PhoneRepairRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.PhoneRepairRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.PhoneRepairRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.PhoneRepairRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.PhoneRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.PhoneRepairRequests", "CampusId", "dbo.Campus", "Id");
            AddForeignKey("dbo.PhoneRepairRequestLifeCycles", "RequestId", "dbo.PhoneRepairRequests", "Id");
            AddForeignKey("dbo.PhoneRepairRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.PhoneNumberAllocationRequests", "CampusId", "dbo.Campus", "Id");
            AddForeignKey("dbo.PhoneNumberAllocationRequestLifeCycles", "RequestId", "dbo.PhoneNumberAllocationRequests", "Id");
            AddForeignKey("dbo.PhoneNumberAllocationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.PhoneLineRepairRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.PhoneLineRepairRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.PhoneLineRepairRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.PhoneLineRepairRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.PhoneLineRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.PhoneLineRepairRequests", "CampusId", "dbo.Campus", "Id");
            AddForeignKey("dbo.PhoneLineRepairRequestLifeCycles", "RequestId", "dbo.PhoneLineRepairRequests", "Id");
            AddForeignKey("dbo.PhoneLineRepairRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.NetworkConnectionRequestLifeCycles", "RequestId", "dbo.NetworkConnectionRequests", "Id");
            AddForeignKey("dbo.NetworkConnectionRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.HoldingPhoneLineRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.HoldingPhoneLineRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.HoldingPhoneLineRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.HoldingPhoneLineRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.HoldingPhoneLineRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.HoldingPhoneLineRequests", "CampusId", "dbo.Campus", "Id");
            AddForeignKey("dbo.HoldingPhoneLineRequestLifeCycles", "RequestId", "dbo.HoldingPhoneLineRequests", "Id");
            AddForeignKey("dbo.HoldingPhoneLineRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.Equipments", "EquipmentTypeId", "dbo.EquipmentTypes", "Id");
            AddForeignKey("dbo.ReplaceEquipments", "EquipmentTypeId", "dbo.EquipmentTypes", "Id");
            AddForeignKey("dbo.EquipmentReplaceRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.EquipmentReplaceRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.EquipmentReplaceRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.ReplaceEquipments", "RequestId", "dbo.EquipmentReplaceRequests", "Id");
            AddForeignKey("dbo.EquipmentReplaceRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.EquipmentReplaceRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.EquipmentReplaceRequests", "CampusId", "dbo.Campus", "Id");
            AddForeignKey("dbo.EquipmentReplaceRequestLifeCycles", "RequestId", "dbo.EquipmentReplaceRequests", "Id");
            AddForeignKey("dbo.EquipmentReplaceRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.RepairEquipments", "ConsumableId", "dbo.Consumables", "Id");
            AddForeignKey("dbo.EquipmentRepairRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.EquipmentRepairRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.EquipmentRepairRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.RepairEquipments", "RequestId", "dbo.EquipmentRepairRequests", "Id");
            AddForeignKey("dbo.EquipmentRepairRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.EquipmentRepairRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.EquipmentRepairRequests", "CampusId", "dbo.Campus", "Id");
            AddForeignKey("dbo.EquipmentRepairRequestLifeCycles", "RequestId", "dbo.EquipmentRepairRequests", "Id");
            AddForeignKey("dbo.EquipmentRepairRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.EquipmentRefillRequestLifeCycles", "RequestId", "dbo.EquipmentRefillRequests", "Id");
            AddForeignKey("dbo.EquipmentRefillRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.EquipmentRefillRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.EquipmentRefillRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.EquipmentRefillRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.RefillEquipments", "RequestId", "dbo.EquipmentRefillRequests", "Id");
            AddForeignKey("dbo.EquipmentRefillRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.EquipmentRefillRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.EquipmentRefillRequests", "CampusId", "dbo.Campus", "Id");
            AddForeignKey("dbo.InstallationEquipments", "EquipmentTypeId", "dbo.EquipmentTypes", "Id");
            AddForeignKey("dbo.EquipmentInstallationRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.EquipmentInstallationRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.EquipmentInstallationRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.EquipmentInstallationRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.InstallationEquipments", "RequestId", "dbo.EquipmentInstallationRequests", "Id");
            AddForeignKey("dbo.EquipmentInstallationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.EquipmentInstallationRequests", "CampusId", "dbo.Campus", "Id");
            AddForeignKey("dbo.EquipmentInstallationRequestLifeCycles", "RequestId", "dbo.EquipmentInstallationRequests", "Id");
            AddForeignKey("dbo.EquipmentInstallationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.EmailSizeIncreaseRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.EmailSizeIncreaseRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.EmailSizeIncreaseRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.EmailSizeIncreaseRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.EmailSizeIncreaseRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.EmailSizeIncreaseRequestLifeCycles", "RequestId", "dbo.EmailSizeIncreaseRequests", "Id");
            AddForeignKey("dbo.EmailSizeIncreaseRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.EmailRegistrationRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.EmailRegistrationRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.EmailRegistrationRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.EmailRegistrationRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.EmailRegistrationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.EmailRegistrationRequestLifeCycles", "RequestId", "dbo.EmailRegistrationRequests", "Id");
            AddForeignKey("dbo.EmailRegistrationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.NetworkConnectionRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.NetworkConnectionRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.NetworkConnectionRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.NetworkConnectionRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.NetworkConnectionRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.NetworkConnectionRequests", "CampusId", "dbo.Campus", "Id");
            AddForeignKey("dbo.ConnectionEquipments", "RequestId", "dbo.NetworkConnectionRequests", "Id");
            AddForeignKey("dbo.ConnectionEquipments", "EquipmentTypeId", "dbo.EquipmentTypes", "Id");
            AddForeignKey("dbo.ReplaceComponents", "ComponentId", "dbo.Components", "Id");
            AddForeignKey("dbo.ComponentReplaceRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.ComponentReplaceRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.ComponentReplaceRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.ReplaceComponents", "RequestId", "dbo.ComponentReplaceRequests", "Id");
            AddForeignKey("dbo.ComponentReplaceRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.ComponentReplaceRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.ComponentReplaceRequests", "CampusId", "dbo.Campus", "Id");
            AddForeignKey("dbo.ComponentReplaceRequestLifeCycles", "RequestId", "dbo.ComponentReplaceRequests", "Id");
            AddForeignKey("dbo.ComponentReplaceRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.AccountRegistrationRequestLifeCycles", "RequestId", "dbo.AccountRegistrationRequests", "Id");
            AddForeignKey("dbo.AccountRegistrationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.Accounts", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.AccountPermissions", "PermissionId", "dbo.Permissions", "Id");
            AddForeignKey("dbo.AccountPermissions", "AccountId", "dbo.Accounts", "Id");
            AddForeignKey("dbo.AccountLossRequestLifeCycles", "RequestId", "dbo.AccountLossRequests", "Id");
            AddForeignKey("dbo.AccountLossRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.AccountDisconnectRequestLifeCycles", "RequestId", "dbo.AccountDisconnectRequests", "Id");
            AddForeignKey("dbo.AccountDisconnectRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.AccountCancellationRequestLifeCycles", "RequestId", "dbo.AccountCancellationRequests", "Id");
            AddForeignKey("dbo.AccountCancellationRequestLifeCycles", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.AccountCancellationRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.AccountCancellationRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.AccountCancellationRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.AccountCancellationRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.AccountCancellationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.SoftwareReworkRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.SoftwareReworkRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.SoftwareReworkRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.SoftwareReworkRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.SoftwareReworkRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.SoftwareReworkRequestAttachments", "RequestId", "dbo.SoftwareReworkRequests", "Id");
            AddForeignKey("dbo.SoftwareDevelopmentRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.SoftwareDevelopmentRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.SoftwareDevelopmentRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.SoftwareDevelopmentRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.SoftwareDevelopmentRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.SoftwareDevelopmentRequestAttachments", "RequestId", "dbo.SoftwareDevelopmentRequests", "Id");
            AddForeignKey("dbo.AccountRegistrationRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.AccountRegistrationRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.AccountRegistrationRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.AccountRegistrationRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.AccountRegistrationRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.AccountRegistrationRequestAttachments", "RequestId", "dbo.AccountRegistrationRequests", "Id");
            AddForeignKey("dbo.AccountLossRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.AccountLossRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.AccountLossRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.AccountLossRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.AccountLossRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.AccountLossRequestAttachments", "RequestId", "dbo.AccountLossRequests", "Id");
            AddForeignKey("dbo.SubdivisionExecutors", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.ExecutorGroupMembers", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.ServicesExecutorGroups", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.Categories", "BranchId", "dbo.Branches", "Id");
            AddForeignKey("dbo.ServicesExecutorGroups", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.Services", "CategoryId", "dbo.Categories", "Id");
            AddForeignKey("dbo.ServicesApprovers", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.Employees", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.SubdivisionExecutors", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.ExecutorGroupMembers", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.ServicesApprovers", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.AccountDisconnectRequests", "SubdivisionId", "dbo.Subdivisions", "Id");
            AddForeignKey("dbo.AccountDisconnectRequests", "StatusId", "dbo.Status", "Id");
            AddForeignKey("dbo.AccountDisconnectRequests", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.AccountDisconnectRequests", "PriorityId", "dbo.Priorities", "Id");
            AddForeignKey("dbo.AccountDisconnectRequests", "ExecutorGroupId", "dbo.ExecutorGroups", "Id");
            AddForeignKey("dbo.AccountDisconnectRequestAttachments", "RequestId", "dbo.AccountDisconnectRequests", "Id");
            AddForeignKey("dbo.SoftwareReworkRequestAttachments", "AttachmentId", "dbo.Attachments", "Id");
            AddForeignKey("dbo.SoftwareDevelopmentRequestAttachments", "AttachmentId", "dbo.Attachments", "Id");
            AddForeignKey("dbo.AccountRegistrationRequestAttachments", "AttachmentId", "dbo.Attachments", "Id");
            AddForeignKey("dbo.AccountLossRequestAttachments", "AttachmentId", "dbo.Attachments", "Id");
            AddForeignKey("dbo.AccountDisconnectRequestAttachments", "AttachmentId", "dbo.Attachments", "Id");
            AddForeignKey("dbo.AccountCancellationRequestAttachments", "RequestId", "dbo.AccountCancellationRequests", "Id");
            AddForeignKey("dbo.AccountCancellationRequestAttachments", "AttachmentId", "dbo.Attachments", "Id");
        }
    }
}
